apiVersion: apps/v1
kind: Deployment
metadata:
  name: timesheet-app
  namespace: timesheet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: timesheet-app
  template:
    metadata:
      labels:
        app: timesheet-app
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command: ["sh", "-c", "until nc -z mysqldb 3306; do echo 'attente de MySQL...'; sleep 3; done"]
      containers:
        - name: app
          image: yasminejhinaoui/timesheet-devops:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: jdbc:mysql://mysqldb:3306/timesheet-devops-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: JAVA_TOOL_OPTIONS
              value: -XX:MaxRAMPercentage=75
          readinessProbe:
            httpGet:
              path: /timesheet-devops/actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /timesheet-devops/actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests:
              memory: 384Mi
            limits:
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: timesheet-app
  namespace: timesheet
spec:
  type: NodePort
  selector:
    app: timesheet-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30089
